kind: PersistentVolume
apiVersion: v1
metadata:
  name: conf
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: "/data/sonar/conf"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-conf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 3Gi
