kind: PersistentVolume
apiVersion: v1
metadata:
  name: data
  labels:
    type: local
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: "/data/sonar/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 30Gi
