kind: PersistentVolume
apiVersion: v1
metadata:
  name: extensions
  labels:
    type: local
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: "/data/sonar/extensions"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-extensions
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 30Gi
