apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifactory-data
  labels:
    type: local
spec:
  capacity:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: "/var/opt/jfrog/artifactory"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-artifactory
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
